platform :ios, '9.0'

target 'foodPrototype' do
use_frameworks!

pod 'SnapKit'
pod 'Firebase/Core'
pod 'Firebase/Storage'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/RemoteConfig'
pod 'GoogleSignIn' 
pod 'JSQMessagesViewController'
pod 'FBSDKLoginKit'
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'

end
